### ISSUE TITLE
PALS error with GNPS FBMN network

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/PALS#37]
Hi Joe, 

Not sure why, but this GNPS FBMN job: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=28b6848e90e040ac9d3bb5486464ff58 with attached metadata file does return an error - it apparently cannot find the samples? I am not sure why….the job finished okay….

Cheers Justin

[gnps_group_caries_saliva.zip](https://github.com/glasgowcompbio/PALS/files/4670234/gnps_group_caries_saliva.zip)

**Comment by LiZhihua1982** [comment]
Dear Joe, 
    I also meet this error for my data both MS2LDA and FBMN results.
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=30a1f92e87a047b58ee8c0faf2b4734e   FEATURE-BASED-MOLECULAR-NETWORKING
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6f14abfe0c5f4b3aa206a55c50d2d99e    MS2LDA_MOTIFDB

![image](https://user-images.githubusercontent.com/38903973/84464820-78417a00-acb0-11ea-8264-f923d1252174.png)
![image](https://user-images.githubusercontent.com/38903973/84464838-855e6900-acb0-11ea-85b9-2458c205c5f5.png)

Best regards

Li Zhihua

**Comment by joewandy** [comment]
Thank you for testing PALS @LiZhihua1982! 😀

Could you share your metadata CSV for those two MS2LDA and FBMN results, please? That would make it easier for me to reproduce the problem here.

**Comment by LiZhihua1982** [comment]
Dear Dr.Joe Wandy,
    Thank you very much for your help! Please see the attached! Thanks again!


Best regards

Li Zhihua

************************************************************************************************
Li Zhihua, Ph.D
Associate Professor
Institute of Agro-products Processing Science and Technology,
Sichuan Academy of Agricultural Sciences,
Chengdu, Sichuan province P.R.China, 610066
Tel: +86-13882095953, +86-028-84504258
E-mail: lzh82@hotmail.com








________________________________
发件人: Joe Wandy <notifications@github.com>
发送时间: 2020年6月12日 22:56
收件人: glasgowcompbio/PALS <PALS@noreply.github.com>
抄送: Li Zhihua <lzh82@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [glasgowcompbio/PALS] PALS error with GNPS FBMN network (#37)


Thank you for testing PALS @LiZhihua1982<https://github.com/LiZhihua1982>! 😀

Could you share your metadata CSV for those two MS2LDA and FBMN results, please? That would make it easier for me to reproduce the problem here.

**Comment by joewandy** [comment]
Hi guys,

I pushed some commits to fix the issues above. During my testing, it seems to work now. However it would be great if you could also help to test again just to make sure. Thanks a lot for finding these bugs!! 

@LiZhihua1982 
For some reason, I couldn't receive the attachment, so I created my [own metadata file](https://github.com/glasgowcompbio/PALS/blob/master/notebooks/test_data/GNPS_debug/metadata.csv) based on the sample names. Hopefully it's correct.

@justinjjvanderhooft 
Could you use this [metadata file ](https://github.com/glasgowcompbio/PALS/blob/master/notebooks/test_data/GNPS_debug/gnps_group_caries_saliva_fixed.csv)instead please (it should be .mzXML not .mzML).

**Comment by justinjjvanderhooft** [comment]
Hey @joewandy - it is working now for caries versus healthy. It throws me a key error when selecting the "not applicable" group. As this was selected at first, it looked like it did not work. That "group" is obviously not important, but it would be nice to know what causes the key error. Could it be a space in the grouping name?

**Comment by LiZhihua1982** [comment]
Dear Dr.Joe Wandy
    Thank you very much! It works!

Best regards

Li Zhihua

************************************************************************************************
Li Zhihua, Ph.D
Associate Professor
Institute of Agro-products Processing Science and Technology,
Sichuan Academy of Agricultural Sciences,
Chengdu, Sichuan province P.R.China, 610066
Tel: +86-13882095953, +86-028-84504258
E-mail: lzh82@hotmail.com








________________________________
发件人: Joe Wandy <notifications@github.com>
发送时间: 2020年6月15日 19:30
收件人: glasgowcompbio/PALS <PALS@noreply.github.com>
抄送: Li Zhihua <lzh82@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [glasgowcompbio/PALS] PALS error with GNPS FBMN network (#37)


Hi guys,

I pushed some commits to fix the issues above. During my testing, it seems to work now. However it would be great if you could also help to test again just to make sure. Thanks a lot for finding these bugs!!

@LiZhihua1982<https://github.com/LiZhihua1982>
For some reason, I couldn't receive the attachment, so I created my own metadata file<https://github.com/glasgowcompbio/PALS/blob/master/notebooks/test_data/GNPS_debug/metadata.csv> based on the sample names. Hopefully it's correct.

@justinjjvanderhooft<https://github.com/justinjjvanderhooft>
Could you use this metadata file <https://github.com/glasgowcompbio/PALS/blob/master/notebooks/test_data/GNPS_debug/gnps_group_caries_saliva_fixed.csv> instead please (it should be .mzXML not .mzML).

―

**Comment by joewandy** [comment]
> Could it be a space in the grouping name?

It's not the space in the grouping name. It's because there are no columns in the peak table that correspond to these blanks and QC samples (I guess they have been removed during processing on GNPS?). So it's best not to include them as a group in the metadata file too.

On the front-end, instead of showing the error message, I also added some text to warn users when this happens. 

![image](https://user-images.githubusercontent.com/2523391/84657571-5fcd9b80-af0c-11ea-9608-4d9f3283898f.png)

**Comment by justinjjvanderhooft** [comment]
I think that solves the issue neatly!

**Comment by LiZhihua1982** [comment]
I use the same metadata as before which it reported error. but now it is OK! Thank you very much!

************************************************************************************************
Li Zhihua, Ph.D
Associate Professor
Institute of Agro-products Processing Science and Technology,
Sichuan Academy of Agricultural Sciences,
Chengdu, Sichuan province P.R.China, 610066
Tel: +86-13882095953, +86-028-84504258
E-mail: lzh82@hotmail.com








________________________________
发件人: Joe Wandy <notifications@github.com>
发送时间: 2020年6月15日 20:31
收件人: glasgowcompbio/PALS <PALS@noreply.github.com>
抄送: Li Zhihua <lzh82@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [glasgowcompbio/PALS] PALS error with GNPS FBMN network (#37)


Could it be a space in the grouping name?

It's not the space in the grouping name. It's because there are no columns in the peak table that correspond to these blanks and QC samples (I guess they have been removed during processing on GNPS?). So it's best not to include them as a group in the metadata file too.

On the front-end, instead of showing the error message, I also added some text to warn users when this happens.

[image]<https://user-images.githubusercontent.com/2523391/84657571-5fcd9b80-af0c-11ea-9608-4d9f3283898f.png>

―
